"""14_Exploring Python Data Types"""

a = 15
str = "Samarth"
flt = 3.14
arr = [10,20,30]
b = 20,40,60
c = True
d = False

print(f'type of {a} = {type(a)}')
print(f'type of {str} = {type(str)}')
print(f'type of {flt} = {type(flt)}')
print(f'type of {arr} = {type(arr)}')
print(f'type of {b} = {type(b)}')
print(f'type of {c} = {type(c)}')
print(f'type of {d} = {type(d)}')

"""
output

type of 15 = <class 'int'>
type of Samarth = <class 'str'>
type of 3.14 = <class 'float'>
type of [10, 20, 30] = <class 'list'>
type of (20, 40, 60) = <class 'tuple'>
type of True = <class 'bool'>
type of False = <class 'bool'>
"""